name: bulloak

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Testing Tree Structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Bulloak
        run: |
          BULLOAK_VERSION="0.9.2"
          if ! bulloak --version 2>/dev/null | grep -q "$BULLOAK_VERSION"; then
            cargo install bulloak@$BULLOAK_VERSION --force
          fi
        id: install-bulloak

      - name: Run Bulloak checks
        run: bulloak check $(find test -type f -name "*.tree")
        id: check
